function gwtmobileproject(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Db='&',ic='.cache.html',_='/',lb='//',Zb='5F765E0812D47F786B70982BB146C9D1',$b='85FCC425120FE9B59BD49A69ED32E4AB',_b='925DB9324AC892D83AC4BFC1791FFFD8',ac='9E5F75391869BD64E0A736F111AC726F',hc=':',pb='::',qc='<script defer="defer">gwtmobileproject.onInjectionDone(\'gwtmobileproject\')<\/script>',hb='<script id="',sb='=',$='?',ub='Bad handler "',bc='C4B8933192EA283D3E0E7887AF59F897',cc='C903E08FF2546B39218CCBDA1E9CAABC',dc='CF925D06A246198CBC1762A5A7A5C400',ec='D22D6442CAA3665B7FE95C71E2F66122',fc='D6030F22254AE5B1C4F450AB451D30AD',pc='DOMContentLoaded',gc='FF9CF0EB1C16B54AE99CDBC94211B1B5',jb='SCRIPT',gb='__gwt_marker_gwtmobileproject',Jb='android',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',Kb='desktop',Y='end',Cb='formfactor',Tb='gecko',Ub='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',jc='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Q='gwtmobileproject',eb='gwtmobileproject.nocache.js',ob='gwtmobileproject::',oc='head',Xb='hosted.html?gwtmobileproject',nc='href',Sb='ie6',Rb='ie8',Qb='ie9',yb='iframe',ab='img',Hb='ipad',Eb='iphone',Fb='ipod',zb="javascript:''",kc='link',Wb='loadExternalRefs',mb='meta',Gb='mobile',Bb='moduleRequested',X='moduleStartup',Pb='msie',nb='name',Mb='opera',Ab='position:absolute;width:0;height:0;border:none',lc='rel',Ob='safari',db='script',Yb='selectingPermutation',R='startup',mc='stylesheet',Ib='tablet',fb='undefined',Vb='unknown',Lb='user.agent',Nb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}gwtmobileproject=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=location.search;var b=a.indexOf(Cb);if(b>=0){var c=a.substring(b);var d=c.indexOf(sb)+1;var e=c.indexOf(Db);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Eb)!=-1||f.indexOf(Fb)!=-1){return Gb}else if(f.indexOf(Hb)!=-1){return Ib}else if(f.indexOf(Jb)!=-1||f.indexOf(Gb)!=-1){var g=160;var h=m.screen.width/g;var i=m.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<6?Gb:Ib}return Kb};v[Cb]={desktop:0,mobile:1,tablet:2};w[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Mb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=9}())return Qb;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;return Vb};v[Lb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};gwtmobileproject.onScriptLoad=function(){if(I){r=true;C()}};gwtmobileproject.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Xb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Yb});if(!B()){try{G([Kb,Mb],Zb);G([Kb,Ob],$b);G([Gb,Ob],_b);G([Kb,Rb],ac);G([Kb,Ub],bc);G([Ib,Ob],cc);G([Gb,Ub],dc);G([Kb,Sb],ec);G([Ib,Ub],fc);G([Kb,Qb],gc);K=x[H(Cb)][H(Lb)];var M=K.indexOf(hc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ic}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[jc]){var a=n.createElement(kc);__gwt_stylesLoaded[jc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,t+jc);n.getElementsByTagName(oc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(pc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(pc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:T});n.write(qc)}
gwtmobileproject();